language: java
jdk: openjdk14
services: docker
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: ./gradlew build --no-daemon --max-workers 2 --scan
notifications:
  email: false
  slack:
    rooms:
      secure: kAszcx7PQQUdEP9F/hFql9IAiOlXCwEFJksfs+JLvB5z+67GT0CuDZsE1xhQlm27vBbD9bSL1AUEpeFdpV7q05PrzfNXpi1odT4wB9yRgHmy73ToX2E2KARp5+m1zRlpSmCy1mTpBIguG04q0FP+qaCZlsass8uhIY2g6YyQ+OzWrlOXHn3P3AMXjIWhK9qxEVzKLxSeYfUhnUbKBwYT/5x4gbbA+HLvCZKrU0y62CSNSj7tFyebucaS6rGcf3DuYGSOvVXcP+safklTZFQYl0BntEjyB6BET7ivRoM3y7Z3SLVFP7B/Obd+PkUxV43GvP6EDkyRuk9Nt281m6XKGCUW/el+SIWHZkHW1uiy3D2nWQKcbUQ+VxfNRIRZWNJWIUyDtIJws6mAjnskyM5IwKs89mG4KE9tVjR7bFoYjS9BecyV6b+IOJ/HjCNlNIhEXPvpaYnCo23Qnn5mJNUGMWyN/ltqBvNsOv+6vOutjaS0VNlqQv5syEIIoLt7yjcRl0MIVbImB8VLcgLrailMoVhW1PAuLQfap0nqEs8mB3wzVNklZmNrYB0DHxoQ+qQ8tjsZP/Qve+chSVp86kyqPkFo7VAa3v96t3wv9zYsfr+n47xWh83lNZvUZzUFct36iE7nOgIU6VArPLZuy//mNGNp48wQ6fA5O48u1FFnJs0=
    on_success: change
    on_failure: change